project    			= "my-elasticsearch"
region     			= "ap-southeast-1"
region_code 		= "sg"
az     	   			= "ap-southeast-1a"
cidr_block 			= "10.0.0.0/16"
subnet_cidr_block 	= "10.0.1.0/24"
public_key_path 	= "./singapore-region-key-pair.pub"
private_key_path 	= "./singapore-region-key-pair"